Create a django app (seabee_gps) and models for the ship_coordinates …
hub-developer/seabee_gps pull request #1
Opened 2021-11-10 13:25 UTC by hub-developer

Clickup task: https://app.clickup.com/t/1rhkmgb
Feature Specs: https://docs.google.com/document/d/1g6j_DZXikoWRtL4hym6yPlqbb_lnZdlnGtsoej_J1nY/edit#

- Create project SeaBeeGPS.
- Create app seabee_gps.
- Create models for ship_coordinates and device table

2021-11-10 13:40 UTC, aybansuarez requested changes

2021-11-10 13:40 UTC, aybansuarez commented on seabee_gps/urls.py
> +    path('maps/', include('maps.urls', namespace='maps')),
`maps.urls` have two different paths?

2021-11-10 19:45 UTC, jeleonardo requested changes

2021-11-10 19:45 UTC, jeleonardo commented on maps/models.py
> +    latitude = models.DecimalField(
Django has a robust feature for this. Let's use geodjango. There's a field there designed for this.

https://docs.djangoproject.com/en/3.2/ref/contrib/gis/model-api/#pointfield

2021-11-10 19:45 UTC, jeleonardo commented on maps/templates/maps_view.html
> +                center: new google.maps.LatLng(49.214439, -2.131250)
Is the place location `49.214439, -2.131250` fine as default?

2021-11-11 08:43 UTC, fdquiachon commented on seabee_gps/urls.py
> +    path('maps/', include('maps.urls', namespace='maps')),
will remove the maps/ one and retain the default home page

2021-11-11 10:57 UTC, fdquiachon commented on maps/templates/maps_view.html
> +                center: new google.maps.LatLng(49.214439, -2.131250)
Yes, that's the default center of our maps wherein it's located in Jersey Island, UK and it zoomed out to cover the area of UK and French coastlines. :) 

This map_views.html is just an initial template, this will still be overridden later on, on the next tasks for Maps plotting task.
https://app.clickup.com/t/1rhkmgb

2021-11-11 11:36 UTC, fdquiachon commented on maps/models.py
> +    latitude = models.DecimalField(
👍  will apply this!

2021-11-11 14:05 UTC, aybansuarez approved these changes

2021-11-11 14:20 UTC, jeleonardo requested changes

2021-11-11 14:20 UTC, jeleonardo commented on seabee_gps/settings.py
> +    'maps'
I believe since it was introduced in 1.7, the recommended way is to use the config class to specify it explicitly.

2021-11-11 14:20 UTC, jeleonardo commented on maps/views.py
> +    template_name = "maps_view.html"
Let's use single quotes for non docstrings for consistency.

2021-11-11 14:20 UTC, jeleonardo commented on seabee_gps/settings.py
> +from decouple import config
Let's include this in requirements.txt

2021-11-11 14:52 UTC, fdquiachon commented on seabee_gps/settings.py
> +from decouple import config
Aha! thanks!

2021-11-11 15:00 UTC, fdquiachon commented on maps/models.py
> +class Devices(models.Model):
It can contain multiple devices.

2021-11-13 02:02 UTC, jeleonardo approved these changes

2021-11-26 05:52 UTC, hub-developer commented
Changed framework from django to react + django-rest

2021-11-26 05:52 UTC, closed without merging